name: Build ComfyUI Desktop
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  get-version:
    name: Get Version from pyproject.toml
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Extract version
        id: get_version
        run: |
          VERSION=$(grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
  build-windows:
    name: Build ComfyUI Desktop - ${{ matrix.target }}
    runs-on: windows-latest
    needs: get-version
    strategy:
      matrix:
        target: [nvidia, amd, cpu]
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run build script
        run: |
          cd ${{ github.workspace }}
          .\scripts\build_comfyui_desktop.cmd
        shell: cmd
        env:
          NUNCHAKU_VERSION: ${{ needs.get-version.outputs.version }}
          BUILD_TARGET: ${{ matrix.target }}
      - name: List build output
        run: |
          Get-ChildItem -Path desktop\out -Recurse | Format-Table Name, Length, LastWriteTime
        shell: pwsh
        if: always()
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: comfyui-desktop-windows-${{ matrix.target }}
          path: desktop/out/make/**/*
          retention-days: 7
        if: success()
      - name: Create Release (on tag push)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: desktop/out/make/**/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
